const weatherData = {
  tempUnit: "C",
  windSpeedUnit: "m/s",
  days: [
    {
      day: "Mon",
      temp: 23,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Tue",
      temp: 22,
      windDirection: "south-east",
      windSpeed: 12,
      type: "windy",
    },
    {
      day: "Wed",
      temp: 22,
      windDirection: "south-west",
      windSpeed: 10,
      type: "rainy",
    },
    {
      day: "Thu",
      temp: 22,
      windDirection: "north-west",
      windSpeed: 10,
      type: "snowy",
    },
    {
      day: "Fri",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Sat",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Sun",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Mon",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Tue",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Wed",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Thu",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Fri",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Sat",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Sun",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Mon",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Tue",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Wed",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Thu",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Fri",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Sat",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Sun",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Mon",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Tue",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Wed",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Thu",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Fri",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Sat",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Sun",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Mon",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Tue",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
    {
      day: "Wed",
      temp: 22,
      windDirection: "north-east",
      windSpeed: 10,
      type: "sunny",
    },
  ],
};

export default weatherData;
